// Typelizer digest f86e03bd2b11d538f61bf692780929c7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Chat = {
  id: number;
  model_id: string;
  created_at: string;
  title?: string;
  last_message_content: unknown;
}

export default Chat;
