// Typelizer digest 0a0311abd103279dbff26614c03e6c99
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Chat = {
  id: number;
  model_id: string;
  created_at: string;
  title?: string;
  last_message_content: string | null;
}

export default Chat;
