// Typelizer digest 7ae6b70a3fbbf20cf9fa66d8bbfb8b1f
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Message = {
  id: number;
  role: string;
  content: string;
  created_at: string;
  last_message_content: unknown;
}

export default Message;
