// Typelizer digest 19ab454003f7ddfb6f868d7253bbcf04
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Message = {
  id: number;
  role: string;
  content: string;
  created_at: string;
}

export default Message;
